//! Unicode character properties, from winkin's own packed tables.
//!
//! Each code point has two `u32` words, generated by `support/unicode_gen`
//! from icu_properties 2.3 (Unicode 17.0) into [`tables`]. The sweep test in
//! `tests.rs` checks them against it for every character.
//!
//! Each word is one three-level lookup: three dependent loads in every
//! plane. icu_properties costs a trie or an inversion list per property, and
//! an out-of-line call for any trie above U+0FFF.
//!
//! The core word, read as [`CoreProps`], holds what the analysis loop reads
//! for every character. The rare word, read as [`RareProps`], holds what it
//! reads per cluster or behind a gate.
//! Reading a field is a shift and a mask. Nothing here allocates, and no
//! `char` can make a lookup panic. Every array read has a fallback, even
//! though the sweep test shows none is ever taken.
//!
//! # The core word
//!
//! | Bits | Field | Accessor |
//! |---:|---|---|
//! | 0..5 | bidi class, ICU4C's `UCharDirection` numbering, as [`bidi`] numbers it | [`CoreProps::bidi_class`] |
//! | 5..15 | script, or a Script_Extensions set id plus `SCRIPT_COUNT` | [`CoreProps::scripts`] |
//! | 15..22 | bracket pair id plus one, or zero for none | [`CoreProps::bracket_pair`] |
//! | 22 | the bracket opens its pair | [`CoreProps::opens_bracket`] |
//! | 23 | Regional_Indicator | [`CoreProps::is_regional_indicator`] |
//! | 24 | Extended_Pictographic | [`CoreProps::is_extended_pictographic`] |
//! | 25 | Emoji_Presentation | [`CoreProps::is_emoji_presentation`] |
//! | 26 | paragraph separator | [`CoreProps::is_paragraph_separator`] |
//! | 27 | White_Space | [`CoreProps::is_white_space`] |
//! | 28 | Line_Break = SA | [`CoreProps::is_complex_context`] |
//! | 29 | General_Category Mn, Mc or Me | [`CoreProps::is_mark`] |
//! | 30 | Emoji | [`CoreProps::is_emoji`] |
//! | 31 | zero | |
//!
//! # The rare word
//!
//! | Bits | Field | Accessor |
//! |---:|---|---|
//! | 0 | Joining_Type = Join_Causing | [`RareProps::is_join_causing`] |
//! | 1 | East_Asian_Width = Wide or Fullwidth | [`RareProps::is_wide`] |
//! | 2 | Vertical_Orientation = U, Tu or Tr | [`RareProps::is_mixed_upright`] |
//! | 3 | Line_Break = CJ | [`RareProps::is_conditional_japanese_starter`] |
//! | 4 | Line_Break = GL, WJ or ZWJ | [`RareProps::is_glue`] |
//! | 5 | Emoji_Modifier_Base | reserved: `RareProps::is_emoji_modifier_base` |
//! | 6 | Emoji_Component | reserved: `RareProps::is_emoji_component` |
//! | 7 | Default_Ignorable_Code_Point | [`RareProps::is_default_ignorable`] |
//! | 8..12 | Grapheme_Cluster_Break | [`RareProps::grapheme_cluster_break`] |
//! | 12..14 | Indic_Conjunct_Break | reserved: `RareProps::indic_conjunct_break` |
//! | 14..17 | East Asian spacing (UTR #59, as Chrome derives it) | [`RareProps::east_asian_spacing`] |
//! | 17..21 | the text-spacing class (CSS Text 4, as Blink numbers it) | [`RareProps::text_spacing`] |
//! | 21..24 | the emphasis class (`text-emphasis-skip`) | [`RareProps::emphasis`] |
//! | 24..26 | the first-letter class (`::first-letter`) | [`RareProps::first_letter`] |
//! | 26..32 | zero | |
//!
//! The enumerated properties are numbered as ICU4C numbers them, and each enum
//! here carries those numbers as its discriminants. The exception is
//! Grapheme_Cluster_Break, whose ZWJ is 13 rather than ICU4C's 17 so that it
//! fits in four bits. A property every stage asks one question of is that
//! question's bit, not the property. The generator's documentation has the
//! reasons for each choice.
//!
//! The reserved fields keep the table's shape for a grapheme segmenter of
//! this crate's own. Nothing asks for them yet, so only the sweep test reads
//! them, and their accessors are compiled for the tests alone.
//!
//! [`segmenters`] chooses the ICU4X line and word segmenters. It is the one
//! place the `dictionaries` feature is read. It also holds what word
//! segmenting asks of a character, and the word boundaries Chrome's rules
//! find.
//!
//! [`normalize`] holds what font coverage asks of canonical normalization:
//! the pairwise steps harfrust's normalizer is built on, and the classes it
//! reorders marks by.

mod bidi;
mod normalize;
mod segmenters;
mod tables;

#[cfg(test)]
mod tests;

pub(crate) use bidi::{
    BIDI_MASK, BidiBracket, BidiClass, BidiScratch, Unit, cluster_bidi_class, reorder_bidi,
    resolve_bidi,
};
pub(crate) use normalize::{
    MAX_DECOMPOSITION, compose, decompose, is_default_ignorable, is_mark, is_variation_selector,
    modified_combining_class,
};
pub(crate) use segmenters::{
    has_stand_ins, is_complex, line_segmenter, segmenter_char, word_boundaries, word_segmenter,
};

use crate::data::{Id, define_id};

/// The core word of `ch`: the fields the analysis loop reads for every
/// character.
#[inline]
pub(crate) fn core_props(ch: char) -> CoreProps {
    CoreProps(tables::core_word(ch))
}

/// The rare word of `ch`: the fields read per cluster, or behind a gate.
#[inline]
pub(crate) fn rare_props(ch: char) -> RareProps {
    RareProps(tables::rare_word(ch))
}

/// The Script of `props`'s character.
///
/// Common or Inherited for a character shared between scripts; resolving
/// those against their neighbours is itemization's job, which reads
/// [`script_extensions`] for the scripts a shared character may take.
pub(crate) fn script(props: CoreProps) -> ScriptId {
    let scripts = props.scripts();
    match scripts.single() {
        Some(script) => script,
        None => match scripts.set_run().first() {
            Some(script) => *script,
            None => ScriptId::UNKNOWN,
        },
    }
}

/// The ISO 15924 tag of `props`'s character's Script.
#[cfg(test)]
fn script_tag(props: CoreProps) -> [u8; 4] {
    script(props).tag()
}

/// The Script_Extensions of `props`'s character, in ICU's order.
///
/// For a character with none of its own, this is its Script alone, as UAX #24
/// defines it. A character whose Script is Common or Inherited but which is
/// used by only some scripts lists those scripts and not its Script.
pub(crate) fn script_extensions(props: CoreProps) -> &'static [ScriptId] {
    let scripts = props.scripts();
    match scripts.single() {
        // `SCRIPT_RUNS` begins with every script alone, in value order.
        Some(script) => {
            let at = script.get();
            tables::SCRIPT_RUNS.get(at..at + 1).unwrap_or(&[])
        }
        None => scripts.set_run().get(1..).unwrap_or(&[]),
    }
}

/// The closing bracket of `props`'s character's pair, if it is a bracket.
///
/// An opening bracket and its closing bracket both answer the closing one, in
/// canonical form: U+2329 and U+232A answer U+3009, as U+3008 does.
fn closing_bracket(props: CoreProps) -> Option<char> {
    let pair = props.bracket_pair()?;
    tables::BRACKET_CLOSINGS.get(pair.get()).copied()
}

/// What the analysis loop reads of a character, for every character.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub(crate) struct CoreProps(u32);

impl CoreProps {
    /// Bidi_Class, as the bidi resolver takes it.
    ///
    /// The word holds it in ICU4C's `UCharDirection` numbering, L 0, R 1,
    /// EN 2, ES 3, ET 4, AN 5, CS 6, B 7, S 8, WS 9, ON 10, LRE 11, LRO 12,
    /// AL 13, RLE 14, RLO 15, PDF 16, NSM 17, BN 18, FSI 19, LRI 20, RLI 21,
    /// PDI 22, which is the numbering [`BidiClass`] is defined in, so it
    /// arrives in the resolver's own type with no conversion.
    #[inline]
    pub(crate) const fn bidi_class(self) -> BidiClass {
        BidiClass::new(((self.0 >> tables::BIDI_CLASS_SHIFT) & tables::BIDI_CLASS_MASK) as u8)
    }

    /// The character's Script and Script_Extensions, as the word holds them.
    #[inline]
    pub(crate) const fn scripts(self) -> ScriptWithExt {
        ScriptWithExt(((self.0 >> tables::SCRIPT_SHIFT) & tables::SCRIPT_MASK) as u16)
    }

    /// The bracket pair the character belongs to, for rule N0, or `None` if
    /// it is not a paired bracket.
    #[inline]
    pub(crate) const fn bracket_pair(self) -> Option<BracketPairId> {
        match (self.0 >> tables::BRACKET_PAIR_SHIFT) & tables::BRACKET_PAIR_MASK {
            0 => None,
            stored => Some(BracketPairId((stored - 1) as u8)),
        }
    }

    /// Whether the character opens its bracket pair rather than closing it.
    #[inline]
    pub(crate) const fn opens_bracket(self) -> bool {
        self.0 & tables::OPENS_BRACKET != 0
    }

    /// The character as the bidi resolver's rule N0 reads a paired bracket,
    /// at position `index` in its paragraph's units: its pair's closing
    /// character, as [`closing_bracket`] gives it, and whether it opens the
    /// pair. `None` if it is not a paired bracket.
    #[inline]
    pub(crate) fn bidi_bracket(self, index: u32) -> Option<BidiBracket> {
        Some(BidiBracket {
            index,
            closing: closing_bracket(self)?,
            is_open: self.opens_bracket(),
        })
    }

    /// Regional_Indicator: half of a flag.
    #[inline]
    pub(crate) const fn is_regional_indicator(self) -> bool {
        self.0 & tables::REGIONAL_INDICATOR != 0
    }

    /// Extended_Pictographic: a pictograph, emoji or not, which a ZWJ
    /// sequence may join.
    #[inline]
    pub(crate) const fn is_extended_pictographic(self) -> bool {
        self.0 & tables::EXTENDED_PICTOGRAPHIC != 0
    }

    /// Emoji_Presentation: shown as emoji unless a variation selector says
    /// otherwise.
    #[inline]
    pub(crate) const fn is_emoji_presentation(self) -> bool {
        self.0 & tables::EMOJI_PRESENTATION != 0
    }

    /// Whether the character forces a line break, and so ends a paragraph:
    /// LF, VT, FF, CR, NEL, U+2028 or U+2029.
    ///
    /// These are UAX #14's mandatory breaks (Line_Break BK, CR, LF and NL),
    /// so a forced line break and a bidi paragraph end coincide. U+001C to
    /// U+001E are not among them: they are bidi class B but break no line,
    /// so they end a bidi paragraph alone.
    #[inline]
    pub(crate) const fn is_paragraph_separator(self) -> bool {
        self.0 & tables::PARAGRAPH_SEPARATOR != 0
    }

    /// White_Space.
    #[inline]
    pub(crate) const fn is_white_space(self) -> bool {
        self.0 & tables::WHITE_SPACE != 0
    }

    /// Line_Break = SA: Thai, Lao, Khmer, Myanmar and the like.
    ///
    /// Their line and word breaks need ICU's dictionaries or its LSTM. The
    /// line segmenter finds these characters for itself. Word motion asks
    /// for them to segment a run of them whole ([`segmenters::is_complex`]).
    #[inline]
    pub(crate) const fn is_complex_context(self) -> bool {
        self.0 & tables::COMPLEX_CONTEXT != 0
    }

    /// General_Category Mn, Mc or Me: a mark.
    ///
    /// harfrust's normalizer clusters a mark with the character before it
    /// and composes it onto a starter. Font coverage replays the normalizer
    /// by this bit ([`normalize`]).
    #[inline]
    const fn is_mark(self) -> bool {
        self.0 & tables::MARK != 0
    }

    /// Emoji: an emoji in either presentation, which `font-variant-emoji`
    /// forces a form on as Chrome does (`Character::IsEmoji`).
    ///
    /// It covers every Emoji_Presentation character, the
    /// Extended_Pictographic characters that are emoji, and the keycap bases
    /// `#`, `*` and the digits.
    #[inline]
    pub(crate) const fn is_emoji(self) -> bool {
        self.0 & tables::EMOJI != 0
    }
}

/// What is read of a character per cluster, or behind a gate a paragraph's
/// flags open.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub(crate) struct RareProps(u32);

impl RareProps {
    /// Joining_Type Join_Causing: the tatweel and U+200D ZERO WIDTH JOINER,
    /// which cause a join on both sides with no forms of their own, and
    /// which letter spacing reads as part of the cursive word they are in.
    #[inline]
    pub(crate) const fn is_join_causing(self) -> bool {
        self.0 & tables::JOIN_CAUSING != 0
    }

    /// East_Asian_Width Wide or Fullwidth: ideographs, kana, Hangul, most
    /// emoji and the fullwidth forms, which `text-emphasis-skip: narrow`
    /// marks.
    #[inline]
    pub(crate) const fn is_wide(self) -> bool {
        self.0 & tables::WIDE != 0
    }

    /// Whether the character stands upright in a vertical line under
    /// `text-orientation: mixed`.
    ///
    /// This is Vertical_Orientation U, Tu or Tr, as Blink's
    /// `Character::IsUprightInMixedVertical` takes them. It leaves a Tr
    /// character's vertical form to the font's `vert`. CSS Writing Modes 3,
    /// section 5.1.1 would turn it on its side in a font with none. But the
    /// font's forms are not known before fonts are chosen, and orientation is
    /// fixed in the analysis runs.
    #[inline]
    pub(crate) const fn is_mixed_upright(self) -> bool {
        self.0 & tables::UPRIGHT_IN_MIXED != 0
    }

    /// Line_Break = CJ: small kana and the prolonged sound mark, which may not
    /// start a line under `line-break: normal`.
    #[inline]
    pub(crate) const fn is_conditional_japanese_starter(self) -> bool {
        self.0 & tables::CONDITIONAL_JAPANESE_STARTER != 0
    }

    /// Line_Break GL, WJ or ZWJ: a character that glues its neighbours
    /// together.
    ///
    /// The rule that puts an opportunity either side of an atomic inline
    /// reads it. Among the space separators, only the no-break spaces (GL)
    /// glue.
    #[inline]
    pub(crate) const fn is_glue(self) -> bool {
        self.0 & tables::GLUE != 0
    }

    /// Emoji_Modifier_Base: takes a skin tone modifier.
    #[inline]
    #[cfg(test)]
    const fn is_emoji_modifier_base(self) -> bool {
        self.0 & tables::EMOJI_MODIFIER_BASE != 0
    }

    /// Emoji_Component: part of a keycap, flag, tag or modifier sequence.
    #[inline]
    #[cfg(test)]
    const fn is_emoji_component(self) -> bool {
        self.0 & tables::EMOJI_COMPONENT != 0
    }

    /// Default_Ignorable_Code_Point: drawn as nothing when a font lacks it.
    #[inline]
    pub(crate) const fn is_default_ignorable(self) -> bool {
        self.0 & tables::DEFAULT_IGNORABLE != 0
    }

    /// Grapheme_Cluster_Break: whether a character is a mark extending the
    /// grapheme before it, which font selection asks.
    #[inline]
    pub(crate) const fn grapheme_cluster_break(self) -> GraphemeClusterBreak {
        GraphemeClusterBreak::from_bits(
            (self.0 >> tables::GRAPHEME_CLUSTER_BREAK_SHIFT) & tables::GRAPHEME_CLUSTER_BREAK_MASK,
        )
    }

    /// Indic_Conjunct_Break, reserved for a grapheme segmenter of this
    /// crate's own.
    #[inline]
    #[cfg(test)]
    const fn indic_conjunct_break(self) -> IndicConjunctBreak {
        IndicConjunctBreak::from_bits(
            (self.0 >> tables::INDIC_CONJUNCT_BREAK_SHIFT) & tables::INDIC_CONJUNCT_BREAK_MASK,
        )
    }

    /// The character's East Asian spacing, which `text-autospace` reads.
    #[inline]
    pub(crate) const fn east_asian_spacing(self) -> EastAsianSpacing {
        EastAsianSpacing::from_bits(
            (self.0 >> tables::EAST_ASIAN_SPACING_SHIFT) & tables::EAST_ASIAN_SPACING_MASK,
        )
    }

    /// The character's text-spacing class, which `text-spacing-trim` reads.
    #[inline]
    pub(crate) const fn text_spacing(self) -> TextSpacingClass {
        TextSpacingClass::from_bits(
            (self.0 >> tables::TEXT_SPACING_SHIFT) & tables::TEXT_SPACING_MASK,
        )
    }

    /// Which kind of character `text-emphasis-skip` sees it as.
    #[inline]
    pub(crate) const fn emphasis(self) -> EmphasisClass {
        EmphasisClass::from_bits((self.0 >> tables::EMPHASIS_SHIFT) & tables::EMPHASIS_MASK)
    }

    /// What `::first-letter` makes of the character where it looks for the
    /// end of the first letter.
    #[inline]
    pub(crate) const fn first_letter(self) -> FirstLetterClass {
        FirstLetterClass::from_bits(
            (self.0 >> tables::FIRST_LETTER_SHIFT) & tables::FIRST_LETTER_MASK,
        )
    }
}

define_id! {
    /// A script, in ICU4C's `UScriptCode` numbering, which indexes the table
    /// of script tags.
    ///
    /// Itemization compares these per character, two bytes each, and turns
    /// one into a tag only once per run.
    pub(crate) struct ScriptId(u16);
}

impl ScriptId {
    /// Common (`Zyyy`): punctuation, digits and symbols every script uses.
    pub(crate) const COMMON: Self = Self(tables::SCRIPT_COMMON);
    /// Inherited (`Zinh`): marks that take the script of what they sit on.
    pub(crate) const INHERITED: Self = Self(tables::SCRIPT_INHERITED);
    /// Unknown (`Zzzz`): unassigned code points, private use and the like.
    pub(crate) const UNKNOWN: Self = Self(tables::SCRIPT_UNKNOWN);
    /// Han (`Hani`): the ideographs, and the radicals and marks that go with
    /// them.
    const HAN: Self = Self(tables::SCRIPT_HAN);
    /// Hiragana (`Hira`).
    const HIRAGANA: Self = Self(tables::SCRIPT_HIRAGANA);

    /// The ISO 15924 tag.
    pub(crate) fn tag(self) -> [u8; 4] {
        match tables::SCRIPT_TAGS.get(self.get()) {
            Some(tag) => *tag,
            None => *b"Zzzz",
        }
    }
}

/// A character's Script and Script_Extensions, as the core word holds them.
///
/// ICU's `ScriptWithExtensions` encoding in ten bits. Below `SCRIPT_COUNT`
/// the value is a script, and the character's Script_Extensions is that
/// script alone: most characters, which is why this is inline. At or above,
/// it names a set, one per distinct pair of Script and Script_Extensions,
/// whose run in `SCRIPT_RUNS` is the Script and then the extensions. ICU spends
/// two more bits to keep Common and Inherited out of that run; there are none
/// to spend here.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub(crate) struct ScriptWithExt(u16);

impl ScriptWithExt {
    /// The script, when it is the whole of the character's Script_Extensions,
    /// or `None` when the character has a set of its own.
    #[inline]
    pub(crate) const fn single(self) -> Option<ScriptId> {
        if self.0 < tables::SCRIPT_COUNT {
            Some(ScriptId(self.0))
        } else {
            None
        }
    }

    /// A set's run, its Script and then its Script_Extensions, or nothing for
    /// a single script.
    fn set_run(self) -> &'static [ScriptId] {
        let Some(set) = self.0.checked_sub(tables::SCRIPT_COUNT) else {
            return &[];
        };
        let set = usize::from(set);
        let starts = &tables::SCRIPT_SET_STARTS;
        let (Some(start), Some(end)) = (starts.get(set), starts.get(set + 1)) else {
            return &[];
        };
        tables::SCRIPT_RUNS
            .get(usize::from(*start)..usize::from(*end))
            .unwrap_or(&[])
    }
}

define_id! {
    /// A bracket pair, which indexes the table of closing brackets.
    ///
    /// Both brackets of a pair carry the same id, and so do canonically
    /// equivalent pairs: U+2329 and U+232A carry the id of U+3008 and U+3009.
    /// Rule N0 pairs brackets by comparing it (UAX #9 BD16).
    pub(crate) struct BracketPairId(u8);
}

/// What `text-autospace` sees of a character: UTR #59's East_Asian_Spacing,
/// derived as Chrome 153 derives it, since ICU has no such property yet
/// (`support/unicode_gen` has the derivation).
///
/// Two values are this crate's own. A decimal digit is kept apart from the
/// other narrow characters, so that `ideograph-numeric` and `ideograph-alpha`
/// can be told apart; and a mark is its own value, since Chrome's autospace
/// steps over every mark before it classifies anything.
#[derive(Copy, Clone, PartialEq, Eq, Debug, Default)]
#[repr(u8)]
pub(crate) enum EastAsianSpacing {
    /// Neither side of a seam: punctuation, symbols, spaces, the fullwidth
    /// and halfwidth forms.
    #[default]
    Other = 0,
    /// A letter of a script that sets text with spaces between words: Latin,
    /// Greek, Cyrillic, Arabic and the like.
    Narrow = 1,
    /// A decimal digit that is not full width.
    NarrowDigit = 2,
    /// Other_Punctuation that is narrow in Chinese and other elsewhere.
    Conditional = 3,
    /// An ideograph, kana, Hangul, Bopomofo, Yi and the like.
    Wide = 4,
    /// A combining mark, which takes no part in a seam.
    Mark = 5,
}

impl EastAsianSpacing {
    const fn from_bits(bits: u32) -> Self {
        match bits {
            1 => Self::Narrow,
            2 => Self::NarrowDigit,
            3 => Self::Conditional,
            4 => Self::Wide,
            5 => Self::Mark,
            _ => Self::Other,
        }
    }
}

/// A character's text-spacing class (CSS Text 4, section 8.5), in Blink's
/// `HanKerningCharType` numbering.
///
/// It says which full-width punctuation the character is, and so how
/// `text-spacing-trim` treats it beside other punctuation. Five classes
/// depend on the font: whether its dots and colons sit in the left half or
/// the middle of their em, and whether its curly quotes are full width.
/// Shaping resolves those against the font.
#[derive(Copy, Clone, PartialEq, Eq, Debug, Default)]
#[repr(u8)]
pub(crate) enum TextSpacingClass {
    /// Not punctuation the rule reads.
    #[default]
    Other = 0,
    /// A full-width opening bracket, drawn in the right half of its em.
    Open = 1,
    /// A full-width closing bracket, drawn in the left half.
    Close = 2,
    /// A middle dot or the ideographic space, drawn in the middle.
    Middle = 3,
    /// An opening bracket that is not full width.
    OpenNarrow = 4,
    /// A closing bracket that is not full width.
    CloseNarrow = 5,
    /// The ideographic and fullwidth comma and full stop.
    Dot = 6,
    /// The fullwidth colon.
    Colon = 7,
    /// The fullwidth semicolon.
    Semicolon = 8,
    /// U+2018 and U+201C.
    OpenQuote = 9,
    /// U+2019 and U+201D.
    CloseQuote = 10,
}

impl TextSpacingClass {
    const fn from_bits(bits: u32) -> Self {
        match bits {
            1 => Self::Open,
            2 => Self::Close,
            3 => Self::Middle,
            4 => Self::OpenNarrow,
            5 => Self::CloseNarrow,
            6 => Self::Dot,
            7 => Self::Colon,
            8 => Self::Semicolon,
            9 => Self::OpenQuote,
            10 => Self::CloseQuote,
            _ => Self::Other,
        }
    }
}

/// Which kind of character an emphasis mark may be set over, as
/// `text-emphasis-skip` names them (CSS Text Decoration 4, section 3.5).
///
/// It comes from the character's General_Category. What skipping the
/// initial `spaces punctuation` leaves is what Chrome's
/// `Character::CanReceiveTextEmphasis` marks. `support/unicode_gen` has the
/// derivation.
#[derive(Copy, Clone, PartialEq, Eq, Debug, Default)]
#[repr(u8)]
pub(crate) enum EmphasisClass {
    /// A letter, a digit, a mark, and the punctuation CSS marks anyway (`#`,
    /// `%`, `&`, `@` and their kin).
    #[default]
    Marked = 0,
    /// A space separator, or one of the word separators Chrome lists.
    Space = 1,
    /// Punctuation.
    Punctuation = 2,
    /// A symbol.
    Symbol = 3,
    /// A control, a format character, an unassigned code point, or a line or
    /// paragraph separator: never marked.
    Never = 4,
}

impl EmphasisClass {
    const fn from_bits(bits: u32) -> Self {
        match bits {
            1 => Self::Space,
            2 => Self::Punctuation,
            3 => Self::Symbol,
            4 => Self::Never,
            _ => Self::Marked,
        }
    }
}

/// What `::first-letter` makes of a character, from its General_Category.
///
/// The classes are the groups CSS Pseudo-Elements 4, section 2.2.1 takes
/// with the first letter, as Blink's `FirstLetterPseudoElement` tests them.
#[derive(Copy, Clone, PartialEq, Eq, Debug, Default)]
#[repr(u8)]
pub(crate) enum FirstLetterClass {
    /// Neither punctuation nor a space separator: the first letter, where
    /// one is looked for.
    #[default]
    Other = 0,
    /// A space separator (Zs) other than U+3000 IDEOGRAPHIC SPACE: the
    /// typographic space that may come between the punctuation and the
    /// letter.
    Space = 1,
    /// Opening punctuation (Ps) or a dash (Pd), which goes with the letter
    /// before it and never after.
    Opening = 2,
    /// The rest of the punctuation (Pc, Pe, Pi, Pf, Po), which goes with the
    /// letter on either side of it.
    Punctuation = 3,
}

impl FirstLetterClass {
    const fn from_bits(bits: u32) -> Self {
        match bits {
            1 => Self::Space,
            2 => Self::Opening,
            3 => Self::Punctuation,
            _ => Self::Other,
        }
    }
}

/// Grapheme_Cluster_Break (UAX #29), in ICU4C's numbering except for
/// [`Zwj`](Self::Zwj).
///
/// ICU4C numbers ZWJ 17, after four values Unicode has given no character
/// since 11.0. Four bits hold 0 to 15, so ZWJ is 13 here and the four are
/// absent.
#[derive(Copy, Clone, PartialEq, Eq, Debug, Default)]
#[repr(u8)]
pub(crate) enum GraphemeClusterBreak {
    /// Anything else.
    #[default]
    Other = 0,
    /// Controls and separators, which stand alone.
    Control = 1,
    /// U+000D.
    Cr = 2,
    /// Marks and joiners that extend what precedes them.
    Extend = 3,
    /// A Hangul leading consonant.
    L = 4,
    /// U+000A.
    Lf = 5,
    /// A Hangul LV syllable.
    Lv = 6,
    /// A Hangul LVT syllable.
    Lvt = 7,
    /// A Hangul trailing consonant.
    T = 8,
    /// A Hangul vowel.
    V = 9,
    /// A spacing mark.
    SpacingMark = 10,
    /// A prepended concatenation mark.
    Prepend = 11,
    /// Half of a flag.
    RegionalIndicator = 12,
    /// U+200D ZERO WIDTH JOINER.
    Zwj = 13,
}

impl GraphemeClusterBreak {
    /// Whether a character of the class has a grapheme boundary on both
    /// sides wherever its neighbour's class does too, except inside a CRLF.
    ///
    /// These are Other, Control, CR and LF. Every UAX #29 rule that keeps two
    /// characters together names one of the other classes on one side: an
    /// extender, a joiner, a spacing mark, a prepended character, a regional
    /// indicator, a Hangul jamo or syllable. That lets analysis find most
    /// boundaries without the segmenter.
    #[inline]
    pub(crate) const fn stands_alone(self) -> bool {
        matches!(self, Self::Other | Self::Control | Self::Cr | Self::Lf)
    }

    const fn from_bits(bits: u32) -> Self {
        match bits {
            1 => Self::Control,
            2 => Self::Cr,
            3 => Self::Extend,
            4 => Self::L,
            5 => Self::Lf,
            6 => Self::Lv,
            7 => Self::Lvt,
            8 => Self::T,
            9 => Self::V,
            10 => Self::SpacingMark,
            11 => Self::Prepend,
            12 => Self::RegionalIndicator,
            13 => Self::Zwj,
            _ => Self::Other,
        }
    }
}

/// Indic_Conjunct_Break (UAX #29 GB9c), in ICU4C's numbering.
#[cfg(test)]
#[derive(Copy, Clone, PartialEq, Eq, Debug, Default)]
#[repr(u8)]
enum IndicConjunctBreak {
    /// Takes no part in a conjunct.
    #[default]
    None = 0,
    /// A consonant a conjunct may join.
    Consonant = 1,
    /// A mark that may sit inside a conjunct.
    Extend = 2,
    /// A virama that joins two consonants.
    Linker = 3,
}

#[cfg(test)]
impl IndicConjunctBreak {
    const fn from_bits(bits: u32) -> Self {
        match bits {
            1 => Self::Consonant,
            2 => Self::Extend,
            3 => Self::Linker,
            _ => Self::None,
        }
    }
}
