//! Font bytes in memory, in the shape the Rust font ecosystem passes around.

use alloc::boxed::Box;
use alloc::sync::Arc;
use alloc::vec::Vec;
use core::fmt;

/// Shared font bytes with an identifier.
///
/// Stores an `Arc<dyn AsRef<[u8]> + Send + Sync>`. Cloning shares the
/// allocation and preserves the ID.
///
/// [`new`](Self::new), [`from_arc`](Self::from_arc), and `From` conversions
/// assign a new ID. [`from_raw_parts`](Self::from_raw_parts) preserves a
/// supplied ID for interoperability with other font libraries.
///
/// Generated IDs start at 2⁶³ to avoid IDs generated by Linebender's
/// `Blob`, which start at 1.
#[derive(Clone)]
pub struct FontBytes {
    bytes: Arc<dyn AsRef<[u8]> + Send + Sync>,
    id: u64,
}

impl FontBytes {
    /// Creates shared font bytes with a new ID.
    pub fn new(bytes: impl AsRef<[u8]> + Send + Sync + 'static) -> Self {
        Self::from_arc(Arc::new(bytes))
    }

    /// Wraps a shared byte buffer with a new ID.
    pub fn from_arc(bytes: Arc<dyn AsRef<[u8]> + Send + Sync>) -> Self {
        Self {
            bytes,
            id: next_id(),
        }
    }

    /// Wraps a shared byte buffer with the given ID.
    ///
    /// The caller must ensure that equal IDs refer to the same bytes.
    /// Reusing an ID for different data can cause incorrect cache hits.
    pub fn from_raw_parts(bytes: Arc<dyn AsRef<[u8]> + Send + Sync>, id: u64) -> Self {
        Self { bytes, id }
    }

    /// Returns the bytes.
    pub fn data(&self) -> &[u8] {
        (*self.bytes).as_ref()
    }

    /// Returns the shared byte buffer.
    pub fn arc(&self) -> &Arc<dyn AsRef<[u8]> + Send + Sync> {
        &self.bytes
    }

    /// Returns the byte-source ID.
    pub fn id(&self) -> u64 {
        self.id
    }

    /// Returns the shared byte buffer and its ID.
    pub fn into_raw_parts(self) -> (Arc<dyn AsRef<[u8]> + Send + Sync>, u64) {
        (self.bytes, self.id)
    }

    /// The shared allocation and the bytes, counted as held even where they
    /// are a memory map rather than the heap: from here there is no telling.
    pub(crate) fn heap(&self, seen: &mut crate::heap::Seen) -> usize {
        seen.once(Arc::as_ptr(&self.bytes), || {
            crate::heap::ARC + core::mem::size_of_val(&*self.bytes) + self.data().len()
        })
    }
}

impl fmt::Debug for FontBytes {
    // Megabytes of a font, which would drown whatever printed it.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("FontBytes")
            .field("id", &self.id)
            .field("len", &self.data().len())
            .finish()
    }
}

impl From<Vec<u8>> for FontBytes {
    fn from(bytes: Vec<u8>) -> Self {
        Self::new(bytes)
    }
}

impl From<Box<[u8]>> for FontBytes {
    fn from(bytes: Box<[u8]>) -> Self {
        Self::new(bytes)
    }
}

impl From<&'static [u8]> for FontBytes {
    fn from(bytes: &'static [u8]) -> Self {
        Self::new(bytes)
    }
}

impl From<Arc<[u8]>> for FontBytes {
    fn from(bytes: Arc<[u8]>) -> Self {
        Self::new(bytes)
    }
}

impl From<Arc<dyn AsRef<[u8]> + Send + Sync>> for FontBytes {
    fn from(bytes: Arc<dyn AsRef<[u8]> + Send + Sync>) -> Self {
        Self::from_arc(bytes)
    }
}

/// Where fresh ids start: far above any id linebender's `Blob` counts to.
const FIRST_ID: u64 = 1 << 63;

pub(super) fn next_id() -> u64 {
    use core::sync::atomic::Ordering::Relaxed;
    #[cfg(target_has_atomic = "64")]
    {
        static NEXT: core::sync::atomic::AtomicU64 = core::sync::atomic::AtomicU64::new(0);
        FIRST_ID + NEXT.fetch_add(1, Relaxed)
    }
    // Embedded targets without 64-bit atomics: four billion fonts before a
    // repeat, which none of them will load.
    #[cfg(not(target_has_atomic = "64"))]
    {
        static NEXT: core::sync::atomic::AtomicU32 = core::sync::atomic::AtomicU32::new(0);
        FIRST_ID + u64::from(NEXT.fetch_add(1, Relaxed))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    #[test]
    fn every_fresh_id_is_new_and_clear_of_blob_s() {
        let a = FontBytes::from(vec![1u8, 2, 3]);
        let b = FontBytes::from(vec![1u8, 2, 3]);
        assert_ne!(a.id(), b.id(), "same contents, different buffers");
        assert!(a.id() >= FIRST_ID && b.id() >= FIRST_ID);
        assert_eq!(a.clone().id(), a.id(), "a clone is the same bytes");
    }

    #[test]
    fn raw_parts_round_trip_without_copying_or_renumbering() {
        let bytes: Arc<dyn AsRef<[u8]> + Send + Sync> = Arc::new(vec![7u8; 16]);
        let held = FontBytes::from_raw_parts(bytes.clone(), 42);
        assert_eq!(held.id(), 42);
        assert!(Arc::ptr_eq(held.arc(), &bytes));
        let (back, id) = held.into_raw_parts();
        assert!(Arc::ptr_eq(&back, &bytes));
        assert_eq!(id, 42);
    }

    #[test]
    fn anything_that_derefs_to_bytes_comes_in() {
        static EMBEDDED: [u8; 4] = [0, 1, 0, 0];
        for bytes in [
            FontBytes::from(vec![0u8, 1, 0, 0]),
            FontBytes::from(vec![0u8, 1, 0, 0].into_boxed_slice()),
            FontBytes::from(&EMBEDDED[..]),
            FontBytes::from(Arc::<[u8]>::from(&EMBEDDED[..])),
        ] {
            assert_eq!(bytes.data(), &EMBEDDED);
        }
    }
}
