"""Prints fontwich's table of fontconfig's languages.

    python crates/fontwich/tools/fc_languages.py > crates/fontwich/src/fallback/language_table.rs

fontconfig has an orthography, `fc-lang/<tag>.orth`, for each language it can
sort fonts by; `FC_LANG` is matched against them. The table is their tags in
fontconfig's own spelling (`az-ir`, `zh-hk`), sorted, which is the closed set a
fallback key's language is drawn from. Read from fontconfig's `main` branch.
"""

import json
import urllib.request

HOST = "https://" + "gitlab.freedesktop.org"
TREE = "/api/v4/projects/fontconfig%2Ffontconfig/repository/tree"


def tags():
    names = []
    page = 1
    while True:
        url = f"{HOST}{TREE}?path=fc-lang&per_page=100&page={page}&ref=main"
        entries = json.loads(urllib.request.urlopen(url).read())
        if not entries:
            break
        names += [entry["name"] for entry in entries]
        page += 1
    return sorted(
        name[: -len(".orth")].replace("_", "-").lower()
        for name in names
        if name.endswith(".orth")
    )


def main():
    found = tags()
    print("// Generated by `crates/fontwich/tools/fc_languages.py` from fontconfig's `fc-lang`")
    print("// orthographies; do not edit.")
    print()
    print("/// How many languages fontconfig has an orthography for.")
    print(f"pub(crate) const LANGUAGE_COUNT: usize = {len(found)};")
    print()
    print("/// Every language fontconfig has an orthography for, as fontconfig")
    print("/// spells it, sorted.")
    print("#[rustfmt::skip]")
    print("pub(super) static FC_LANGUAGES: [&str; LANGUAGE_COUNT] = [")
    line = "   "
    for tag in found:
        item = f' "{tag}",'
        if len(line) + len(item) > 99:
            print(line)
            line = "   "
        line += item
    print(line)
    print("];")


if __name__ == "__main__":
    main()
