// Generated by `crates/fontwich/tools/fc_languages.py` from fontconfig's `fc-lang`
// orthographies; do not edit.

/// How many languages fontconfig has an orthography for.
pub(super) const LANGUAGE_COUNT: usize = 341;

/// Every language fontconfig has an orthography for, as fontconfig
/// spells it, sorted.
#[rustfmt::skip]
pub(super) static FC_LANGUAGES: [&str; LANGUAGE_COUNT] = [
    "aa", "ab", "ae", "af", "agr", "aho", "ak", "akk", "am", "an", "anp", "ar", "arc", "as", "ast",
    "av", "ay", "ayc", "az-az", "az-ir", "ba", "ban", "bax", "be", "bem", "ber-dz", "ber-ma", "bg",
    "bh", "bhb", "bho", "bi", "bin", "bku", "blt", "bm", "bn", "bo", "br", "brx", "bs", "bua",
    "byn", "ca", "ccp", "ce", "ch", "chm", "chr", "cjm", "ckb", "cmn", "co", "cop", "crh", "cs",
    "csb", "cu", "cv", "cy", "da", "de", "dmf", "doi", "dsb", "dv", "dz", "ecy", "ee", "egy",
    "eky", "el", "en", "eo", "es", "et", "ett", "eu", "fa", "fat", "ff", "fi", "fil", "fj", "fo",
    "fr", "fur", "fy", "ga", "gd", "gez", "gl", "gmy", "gn", "got", "gu", "gv", "ha", "hak", "haw",
    "he", "hi", "hif", "hit", "hlu", "hmd", "hne", "hnn", "ho", "hoc", "hr", "hsb", "ht", "hu",
    "hy", "hz", "ia", "id", "ie", "ig", "ii", "ik", "io", "is", "it", "iu", "ja", "jv", "ka",
    "kaa", "kab", "kaw", "khb", "ki", "kj", "kk", "kl", "km", "kn", "ko", "kok", "kr", "ks",
    "ku-am", "ku-iq", "ku-ir", "ku-tr", "kum", "kv", "kw", "kwm", "ky", "la", "lah", "lb", "lep",
    "lez", "lg", "li", "lif", "lij", "lis", "ln", "lo", "lt", "lv", "lzh", "mag", "mai", "mfe",
    "mg", "mh", "mhr", "mi", "mid", "miq", "mjw", "mk", "ml", "mn-cn", "mn-mn", "mni", "mnw", "mo",
    "mr", "mro", "ms", "mt", "my", "na", "nan", "nb", "nds", "ne", "ng", "nhn", "niu", "nl", "nn",
    "nnp", "no", "nqo", "nr", "nso", "nv", "ny", "oc", "om", "or", "os", "osa", "ota", "otk",
    "oui", "pa", "pa-pk", "pal", "pap-an", "pap-aw", "peo", "pes", "pgd", "pgl", "phn", "pl",
    "prs", "ps-af", "ps-pk", "pt", "qu", "quz", "raj", "rhg", "rif", "rm", "rn", "ro", "ru", "rw",
    "sa", "sah", "sam", "sat", "sc", "sco", "sd", "se", "sel", "sg", "sgs", "sh", "shn", "shs",
    "si", "sid", "sk", "sl", "sm", "sma", "smj", "smn", "sms", "sn", "so", "sog", "sq", "sr", "ss",
    "st", "su", "sux", "suz", "sv", "sw", "syr", "szl", "ta", "tbw", "tcy", "tdd", "te", "tg",
    "th", "the", "ti-er", "ti-et", "tig", "tk", "tl", "tn", "to", "tpi", "tr", "ts", "tt", "tw",
    "txg", "ty", "tyv", "ug", "uga", "uk", "und-zmth", "und-zsye", "unm", "ur", "uz", "vai", "ve",
    "vi", "vo", "vot", "wa", "wae", "wal", "wen", "wo", "xag", "xco", "xcr", "xh", "xlc", "xld",
    "xmr", "xna", "xpr", "xsa", "xzh", "yap", "yi", "yo", "yue", "yuw", "za", "zh-cn", "zh-hk",
    "zh-mo", "zh-sg", "zh-tw", "zkt", "zu",
];
